apiVersion: v1
kind: Namespace
metadata:
  name: corp-local
  labels:
    # Allow privileged pods (Samba requires SYS_ADMIN capability)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
