#!/bin/bash
set -e

DOMAIN="${SAMBA_DOMAIN:-CORP}"
REALM="${SAMBA_REALM:-CORP.LOCAL}"
ADMIN_PASS="${SAMBA_ADMIN_PASS:-Admin@Corp#1234}"
DATA_DIR="/var/lib/samba"
PROVISION_FLAG="${DATA_DIR}/.provisioned"
SMB_CONF_BACKUP="${DATA_DIR}/smb.conf.bak"  # persisted on PVC

provision_domain() {
    echo "[*] Provisioning Samba AD domain ${REALM}..."
    samba-tool domain provision \
        --use-rfc2307 \
        --realm="${REALM}" \
        --domain="${DOMAIN}" \
        --adminpass="${ADMIN_PASS}" \
        --server-role=dc \
        --dns-backend=SAMBA_INTERNAL \
        --option="dns forwarder = 8.8.8.8"

    # Allow plain LDAP binds from non-Windows clients (ldapjs, Python-ldap, etc.)
    # Samba 4 requires LDAP signing by default; disable for dev/app LDAP access.
    sed -i '/^\[global\]/a \\tldap server require strong auth = no' /etc/samba/smb.conf

    # Persist smb.conf to the PVC so it survives container restarts
    cp /etc/samba/smb.conf "${SMB_CONF_BACKUP}"

    # Copy Kerberos config generated by provision
    cp /var/lib/samba/private/krb5.conf /etc/krb5.conf
    touch "${PROVISION_FLAG}"
    echo "[*] Domain provisioned."
}

seed_users() {
    echo "[*] Seeding test users..."

    # testuser1
    samba-tool user create testuser1 "User@Corp#1" \
        --given-name="Test" \
        --surname="User1" \
        --mail-address="testuser1@${REALM,,}" \
        --department="Engineering" 2>/dev/null || echo "[!] testuser1 already exists"

    # testuser2
    samba-tool user create testuser2 "User@Corp#2" \
        --given-name="Test" \
        --surname="User2" \
        --mail-address="testuser2@${REALM,,}" \
        --department="Engineering" 2>/dev/null || echo "[!] testuser2 already exists"

    # adminuser (member of Domain Admins)
    samba-tool user create adminuser "Admin@Corp#1" \
        --given-name="Admin" \
        --surname="User" \
        --mail-address="adminuser@${REALM,,}" \
        --department="IT" 2>/dev/null || echo "[!] adminuser already exists"

    echo "[*] Adding adminuser to Domain Admins..."
    samba-tool group addmembers "Domain Admins" adminuser 2>/dev/null || true

    echo "[*] Creating AppUsers group..."
    samba-tool group add AppUsers 2>/dev/null || echo "[!] AppUsers already exists"

    echo "[*] Adding testuser1, testuser2 to AppUsers..."
    samba-tool group addmembers AppUsers testuser1,testuser2 2>/dev/null || true

    echo "[*] Users seeded."
}

restore_config() {
    echo "[*] Restoring smb.conf from PVC backup..."
    cp "${SMB_CONF_BACKUP}" /etc/samba/smb.conf
    cp /var/lib/samba/private/krb5.conf /etc/krb5.conf 2>/dev/null || true
}

# --- Main ---

if [ ! -f "${PROVISION_FLAG}" ]; then
    provision_domain
    seed_users
else
    echo "[*] Samba already provisioned."
    restore_config
fi

echo "[*] Starting Samba..."
exec samba --no-process-group -i
